# _config.yml — GitHub Pages SEO optimisé

# --- Site ---
title: "SCOPA Studio — Coworking Gratte-Ciel Villeurbanne"
tagline: "Coworking au cœur des Gratte-Ciel à Villeurbanne"
description: "Espace de coworking à Villeurbanne, quartier des Gratte-Ciel : bureaux flexibles, salles de réunion, café/thé à volonté, accès 24/7, internet haut débit."
lang: fr
locale: fr_FR
url: "https://studio.scopa.co"       # domaine principal
baseurl: ""                          # laisser vide si racine du domaine
permalink: pretty                    # URLs SEO-friendly: /page/

# --- Build ---
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
timezone: Europe/Paris

# --- Plugins autorisés par GitHub Pages ---
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-include-cache

# --- SEO (jekyll-seo-tag) ---
author:
  name: "SCOPA Studio"
  url: "https://studio.scopa.co"
  email: "studio@scopa.co"
logo: /assets/img/og-logo.png         # image carrée 512x512 min
image: /assets/img/og-cover.jpg       # image 1200x630 pour Open Graph (réseaux sociaux)
social:
  name: "SCOPA Studio"
  links:
    - "https://www.linkedin.com/company/scopa-studio/"
    - "mailto:studio@scopa.co"

# --- Defaults: métadonnées & sitemap ---
defaults:
  - scope:
      path: ""
    values:
      lang: fr
      sitemap: true
      layout: default
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: post
      permalink: /blog/:title/

# --- Sitemap ---
# jekyll-sitemap génère automatiquement sitemap.xml basé sur url

# --- Feed (si blog) ---
feed:
  path: feed.xml

# --- Exclusions (fichiers non publiés) ---
exclude:
  - README.md
  - node_modules/
  - package.json
  - package-lock.json
  - vendor/
  - Gemfile
  - Gemfile.lock
  - scripts/
  - .github/

# --- Collections (optionnel si besoin) ---
# collections:
#   offres:
#     output: true
#     permalink: /offres/:name/

# --- Navigation (optionnel si ton thème l'utilise) ---
# nav:
#   - title: Tarifs
#     url: /tarifs/
#   - title: Salles
#     url: /salles/
#   - title: Contact
#     url: /contact/
